# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "DA"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

template: "template_toolkit"

session: Cookie

engines:
  template:
    template_toolkit:
      extension: 'tt'
      INCLUDE_PATH: 'views/'
      start_tag: '<%'
      end_tag:   '%>'
  session:
    Cookie:
      secret_key: your secret passphrase
      default_duration: 604800

plugins:
  Feed:
    title: "Dicionário-Aberto"
    subtitle: "Novidades"
    format: "Atom"
  Database:
    driver: 'mysql'
    database: 'dicionario-aberto'
    port: 3306
    host: 127.0.0.1
    username: 'dicionarioaberto'
    password: 'password'
    dbi_params:
      mysql_enable_utf8: 1
  Emailesque:
      ssl: 1
      driver: 'smtp'
      host: 'smtp.gmail.com'
      port: 465
      user: 'hashashin@gmail.com'
      pass: 'password'






