requires "DA::Database"       => "0";
requires "Dancer2"            => "0.166001";
requires "Dancer2::Plugin::Database"  => "0";
requires "DBD::mysql"         => "0";

recommends "YAML"             => "0";
recommends "URL::Encode::XS"  => "0";
recommends "CGI::Deurl::XS"   => "0";
recommends "HTTP::Parser::XS" => "0";

on "test" => sub {
    requires "Test::More"            => "0";
    requires "HTTP::Request::Common" => "0";
};
